### ISSUE TITLE
CT: Failure to grunt snapshot

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#175]
```
wave-interference : build : phet
Failure to grunt snapshot-1540225114495/wave-interference:
Running "lint-all" task

Running "clean" task

Running "build" task
Building runnable repository (wave-interference, brands: phet)
Building brand: phet
Fatal error: Perennial task failed:
Error: Error: Error: Loader plugin did not call the load callback in the build:
image:
  image!WAVE_INTERFERENCE/plane_wave_source.png: Error: unacceptable license entry for WAVE_INTERFERENCE/plane_wave_source.png
Module loading did not complete for: wave-interference-main, WAVE_INTERFERENCE/slits/SlitsScreen, WAVE_INTERFERENCE/slits/view/SlitsScreenView, WAVE_INTERFERENCE/slits/view/PlaneWaveEmitterNode
  at /data/share/phet/continuous-testing/snapshot-1540225114495/chipper/js/grunt/requireBuild.js:107:15
  at /data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:28083:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:30302:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1389:34)
  at /data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1439:21
  at each (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:309:31)
  at Module.emit (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1438:17)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1188:30)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1264:30)
  at /data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:2697:17
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1540225114495/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)

Full Error details:
{}


Approximately 10/22/2018, 10:18:34 AM
```

**Comment by samreid** [comment]
Thanks @KatieWoe, proposed fix is in https://github.com/phetsims/wave-interference/commit/33c5b0414301f1e733488e5862459b6284ff8928, closing.
