### ISSUE TITLE
Failure during dev deploy

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#360]
```
~/github/projectile-motion$ cd ../wave-interference/
~/github/wave-interference$ grunt dev --brands=phet
Running "dev" task
(Forwarding task to perennial)
Running "dev" task
Fatal error: VPN or being on campus is required for this build. Ensure VPN is enabled, or that you have access to phet-server.int.colorado.edu
Fatal error: perennial grunt "--repo=wave-interference" "dev" "--brands=phet" failed with code 1
~/github/wave-interference$ gret dev
Running "dev" task
(Forwarding task to perennial)
Running "dev" task
info: linting wave-interference
info: running [[ -d "/data/web/htdocs/dev/html/wave-interference" ]] && echo exists || echo not remotely on bayes.colorado.edu
info: running [[ -d "/data/web/htdocs/dev/html/wave-interference/1.1.0-dev.2" ]] && echo exists || echo not remotely on bayes.colorado.edu
Deploy 1.1.0-dev.2 to bayes.colorado.edu [y/N]?y
info: Setting version from package.json for wave-interference to 1.1.0-dev.2
info: git add package.json on wave-interference
info: git commit on wave-interference with message:
Bumping version to 1.1.0-dev.2
info: git push on wave-interference to master
info: npm update on wave-interference
info: npm update on chipper
info: building wave-interference
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (wave-interference, brands: phet)
Building brand: phet
>> require.js optimization for brand: phet complete (5095472 bytes)
>> Minification for phet complete
>> Require.js: 1919912 bytes
>> Preloads: 248063 bytes
>> Mipmaps: 54494 bytes

Done.

info: running mkdir -p "/data/web/htdocs/dev/html/wave-interference" && echo "IndexOrderDefault Descending Date
" > "/data/web/htdocs/dev/html/wave-interference/.htaccess" remotely on bayes.colorado.edu
Fatal error: Perennial task failed:
Error: ssh reids@bayes.colorado.edu mkdir -p "/data/web/htdocs/dev/html/wave-interference" && echo "IndexOrderDefault Descending Date
" > "/data/web/htdocs/dev/html/wave-interference/.htaccess" in . failed with exit code 1 and stdout:

  at ChildProcess.process.on.code (/Users/samreid/github/perennial/js/common/execute.js:72:17)
  at ChildProcess.emit (events.js:160:13)
  at maybeClose (internal/child_process.js:943:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

Full Error details:
{
  "cmd": "ssh",
  "args": [
    "reids@bayes.colorado.edu",
    "mkdir -p \"/data/web/htdocs/dev/html/wave-interference\" && echo \"IndexOrderDefault Descending Date\n\" > \"/data/web/htdocs/dev/html/wave-interference/.htaccess\""
  ],
  "cwd": ".",
  "stdout": "",
  "stderr": "Unmatched \".\nUnmatched \".\n",
  "code": 1
}
Fatal error: perennial grunt "--repo=wave-interference" "--brands=phet" "dev" failed with code 1
```

**Comment by samreid** [comment]
@jessegreenberg said:

> Jesse Greenberg [6:08 PM]
I was just able to deploy a dev version. It looks like it is trying to make a new directory for wave-interference while it already exists.

**Comment by samreid** [comment]
I wonder if having @zepumph deploy a dev version earlier caused some interference?

**Comment by samreid** [comment]
```
[reids@bayes wave-interference]$ cat .htaccess 
IndexOrderDefault Descending Date
 -v

[reids@bayes wave-interference]$ cat ../gas-properties/.htaccess 
IndexOrderDefault Descending Date
```

**Comment by samreid** [comment]
I tried this:
```
[reids@bayes wave-interference]$ cp ../gas-properties/.htaccess ./.htaccess 
[reids@bayes wave-interference]$ cat .htaccess 
IndexOrderDefault Descending Date


```

**Comment by samreid** [comment]
If I just run the command that claims to be failing, it seems to succeed:

```
~/github/wave-interference$ ssh reids@bayes.colorado.edu "mkdir -p \"/data/web/htdocs/dev/html/wave-interference\" && echo \"IndexOrderDefault Descending Date\n\" > \"/data/web/htdocs/dev/html/wave-interference/.htaccess\""
```

**Comment by samreid** [comment]
It looks like it is incorrectly detecting that the sim directory does not exist.  Here is the code from dev.js
```js
  // Create (and fix permissions for) the main simulation directory, if it didn't already exist
  if ( !simPathExists ) {
    await devSsh( `mkdir -p "${simPath}" && echo "IndexOrderDefault Descending Date\n" > "${simPath}/.htaccess"` );
    // await devSsh( `chmod -R g+w "${simPath}"` );
  }
```

That's what's printing out in the error message.  So why does it think the wave-interference directory doesn't exist?

**Comment by samreid** [comment]
On my local:

```
[[ -d "/data/web/htdocs/dev/html/wave-interference" ]] && echo exists || echo not
not
```

On bayes:

```
[reids@bayes ~]$ [[ -d "/data/web/htdocs/dev/html/wave-interference" ]] && echo exists || echo not
[[: Command not found.
not
```

**Comment by samreid** [comment]
On the remote:
```
[reids@bayes ~]$ echo $0
-tcsh
```

Perhaps this was disturbed when @mattpen and I were working on fixing my bayes login.

**Comment by samreid** [comment]
I tried to change my shell but it says I do not exist:

```
[reids@bayes ~]$ chsh
Changing shell for reids.
New shell [/bin/tcsh]: /bin/bash
Password: 
chsh: user "reids" does not exist.
```

**Comment by samreid** [comment]
@mattpen can you please help me set my shell to bash?

**Comment by samreid** [comment]
After chatting with @pixelzoom on slack, we agreed I should try https://unix.stackexchange.com/questions/46645/how-can-i-use-bash-as-my-login-shell-when-my-sysadmin-refuses-to-let-me-change-i

I did this and logged in again and it seemed to have no effect:

```
[reids@bayes ~]$ cat ~.profile 
case $- in
  *i*)
    # Interactive session. Try switching to bash.
    if [ -z "$BASH" ]; then # do nothing if running under bash already
      bash=$(command -v bash)
      if [ -x "$bash" ]; then
        export SHELL="$bash"
        exec "$bash"
      fi
    fi
esac
[reids@bayes ~]$ exit
logout
Connection to bayes.colorado.edu closed.
~/github$ ssh bayes
Last login: Tue Mar 26 19:42:10 2019 from [...]
[reids@bayes ~]$ echo $0
-tcsh
[reids@bayes ~]$ echo $SHELL
/bin/tcsh
```
