### ISSUE TITLE
CT Converting circular structure to JSON

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#492]
Also in Intro
```
wave-interference : build : phet
Failure to grunt snapshot-1584303875452/wave-interference:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (wave-interference, brands: phet)
Building brand: phet
Fatal error: Converting circular structure to JSON

Webpack build errors: [ ModuleNotFoundError: Module not found: Error: Can't resolve '../../../sounds/squishier-button-007_mp3.js' in '/data/share/phet/continuous-testing/snapshot-1584303875452/wave-interference/js/common/view'
  at factory.create (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/webpack/lib/Compilation.js:925:10)
  at factory (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
  at resolver (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
  at asyncLib.parallel (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
  at /data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/neo-async/async.js:2830:7
  at /data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/neo-async/async.js:6877:13
  at normalResolver.resolve (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
  at doResolve (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
  at hook.callAsync (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
  at _fn0 (<anonymous>:15:1)
  at resolver.doResolve (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
  at hook.callAsync (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
  at _fn0 (<anonymous>:15:1)
  at hook.callAsync (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
  at _fn0 (<anonymous>:27:1)
  at resolver.doResolve (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
  at hook.callAsync (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
  at _fn42 (<anonymous>:16:1)
  at hook.callAsync (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
  at _fn0 (<anonymous>:27:1)
  at resolver.doResolve (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
  at hook.callAsync (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
  at _fn1 (<anonymous>:16:1)
  at hook.callAsync (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
  at _fn0 (<anonymous>:15:1)
  at fs.stat (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15)
  at process.nextTick (/data/share/phet/continuous-testing/snapshot-1584303875452/chipper/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15)
  at process._tickCallback (internal/process/next_tick.js:61:11)

resolve '../../../sounds/squishier-button-007_mp3.js' in '/data/share/phet/continuous-testing/snapshot-1584303875452/wave-interference/js/common/view'
  using description file: /data/share/phet/continuous-testing/snapshot-1584303875452/wave-interference/package.json (relative path: ./js/common/view)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /data/share/phet/continuous-testing/snapshot-1584303875452/wave-interference/package.json (relative path: ./sounds/squishier-button-007_mp3.js)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /data/share/phet/continuous-testing/snapshot-1584303875452/wave-interference/sounds/squishier-button-007_mp3.js doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /data/share/phet/continuous-testing/snapshot-1584303875452/wave-interference/sounds/squishier-button-007_mp3.js.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /data/share/phet/continuous-testing/snapshot-1584303875452/wave-interference/sounds/squishier-button-007_mp3.js.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /data/share/phet/continuous-testing/snapshot-1584303875452/wave-interference/sounds/squishier-button-007_mp3.js.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /data/share/phet/continuous-testing/snapshot-1584303875452/wave-interference/sounds/squishier-button-007_mp3.js.json doesn't exist
      as directory
        /data/share/phet/continuous-testing/snapshot-1584303875452/wave-interference/sounds/squishier-button-007_mp3.js doesn't exist ]

Approximately 3/15/2020, 2:24:35 PM
```

**Comment by samreid** [comment]
Should be fixed as part of https://github.com/phetsims/wave-interference/issues/480, closing.
