### ISSUE TITLE
Issues with sound ducking

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#521]
Noted in https://github.com/phetsims/fourier-making-waves/issues/55, where I was asked to use WaveMeterNode.js as an example of how to duck sounds. 

In WaveMeterNode.js:

```js
    // Turn down the water drops, speaker or light sound when the wave meter is being used.
    this.duckingProperty = new DerivedProperty( [ series1PlayingProperty, series2PlayingProperty ], ( a, b ) => {
      if ( a || b ) {
        return 0.3;
      }
      else {
        return 1;
      }
    } );
```

And then that Property is observed elsewhere, to set the output of sound clips.

Problems:

(1) No documentation about the semantics of `duckingProperty` or its type. It's actually `{number}` and it's an output level.

(2) You're assuming (and hardcoding) a default output level of 1.  That's incredibly brittle. 

(3) This could be done without a Property, and with less coupling, by creating a sound category for the 3 clips that you want to duck.  Then use `soundManager.setOutputLevelForCategory` to change their output level.

**Comment by samreid** [comment]
Unassigning until we return our attention to this sim.

**Comment by samreid** [comment]
@jbphet is there a way to add new categories to sound manager? I see that there is an option on initialization, but I'm not sure how to do that, and if not specified there then `setOutputLevelForCategory` will fail with an assertion (if you try to do (3) in the top comment).

**Comment by pixelzoom** [comment]
>  is there a way to add new categories to sound manager?

See `SoundGeneratorAddOptions.categoryName` in soundManager.ts.  While the documentation is lacking, I beleive that you can invent your own category names, because the type is `categoryName?: string | null` and I see no associated string enum or validation. 

Hypothetical example usage:

```ts
new SoundClipPlayer( generalBoundaryBoop_mp3, {
  soundManagerOptions: { categoryName: 'my-custom-category' }
} )
```

or if you're adding to soundManager:

```ts
soundManager.addSoundGenerator( mySoundClip, { categoryName: 'my-custom-category' } );
```

**Comment by pixelzoom** [comment]
I could find only one usage in the PhET code base that is not `categoryName: 'user-interface'`.  In color-vision PerceivedColorNode.ts:

```ts
    // sound generation
    soundManager.addSoundGenerator(
      new PerceivedColorSoundGenerator( perceivedColorProperty, {
        initialOutputLevel: 0.1,
        enabledProperty: simPlayingProperty,
        associatedViewNode: this
      } ), {
        categoryName: 'sim-specific'
      }
    );
```

I'm also not sure how Audio preferences work wrt `categoryName`. Do Audio preferences control only `'user-interface'` or all categories?

**Comment by samreid** [comment]
This change:

```diff
Subject: [PATCH] Add sound effects for wave sensor probe, see https://github.com/phetsims/wave-interference/issues/458
---
Index: wave-interference/js/waves/view/WavesScreenSoundView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/wave-interference/js/waves/view/WavesScreenSoundView.ts b/wave-interference/js/waves/view/WavesScreenSoundView.ts
--- a/wave-interference/js/waves/view/WavesScreenSoundView.ts	(revision da07d3c47a746c10ff6ab7b1b2cfc6f304eddba1)
+++ b/wave-interference/js/waves/view/WavesScreenSoundView.ts	(date 1781886620136)
@@ -156,7 +156,11 @@
         associatedViewNode: view
       } );
 
-      soundManager.addSoundGenerator( lightBeamLoopSoundClip );
+      soundManager.addSoundGenerator( lightBeamLoopSoundClip, {
+        categoryName: 'myCategory'
+      } );
+
+      soundManager.setOutputLevelForCategory( 'myCategory', 0.5 );
 
       const lightAmplitudeProperty = model.lightScene.amplitudeProperty;
       const lightFrequencyProperty = model.lightScene.frequencyProperty;

```

Crashes at runtime like so:

```
Uncaught Error: Assertion failed: category does not exist : myCategory
    at window.assertions.assertFunction (assert.js:48:21)
    at SoundManager.addSoundGenerator (soundManager.ts:424:17)
    at new WavesScreenSoundView (WavesScreenSoundView.ts:159:20)
    at new WavesScreenView (WavesScreenView.ts:691:35)
    at WavesScreen.createView (BaseScreen.ts:43:16)
    at WavesScreen.initializeView (Screen.ts:321:23)
    at Array.<anonymous> (Sim.ts:956:16)
    at Sim.ts:964:24
```

**Comment by jbphet** [comment]
The "custom category" feature is admittedly a bit underdeveloped due to, so far, a lack of interest in it.  @samreid - if you need this, I'd be happy to do some work on it assuming we can get clearance from planning.  I don't think it would require much time.

I just looked through the code and, as @pixelzoom alludes to above, there are options to the function that is used to initialize the sound manager that can be used to specify additional categories for sounds.  However, in looking through how the initialization function is actually invoked in our framework, the options aren't "threaded through", meaning that there isn't currently a way for a sim to specify additional sound categories as options to the initialization function.  I'd suggest doing some or all of the following:
- Improve the creation of the categories in `soundManager.initialize` such that it would be harder or impossible to blow away the "sim-specific" and "user-interface" categories, since they are fairly widely used at this point
- Thread the sound initialization options through the `Sim` constructor and pass them to `soundManager.initialize`
- Add a function to `soundManager` that would allow post-construction addition of sound categories.

@samreid - How does this sound - if I were to do this, would it solve the problem that you're looking at?

**Comment by samreid** [comment]
In my opinion, we should add support for the tambo "custom category" feature as described above, and it would simplify the wave-interference case. That being said, I feel wave-interference is working "as is" and this change, while an improvement, would not be a requirement for production publication. So I will have to defer to @jbphet, please let me know what you think is best.

**Comment by arouinfar** [comment]
> That being said, I feel wave-interference is working "as is" and this change, while an improvement, would not be a requirement for production publication. 

I agree, so I will mark this issue as deferred. This can wait until the next release.
